apiVersion: v1
kind: PersistentVolume
metadata:
  name: argo-pv
spec:
  storageClassName: argo-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/argo-volume/